version: '3.7'

services:
  redis:
    container_name: redis
    image: redis
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - shadow
    restart: always

  shadow-localstack:
    image: localstack/localstack:latest
    container_name: shadow-localstack
    ports:
      - '4568:4568'
      - '4575:4575'
      - '4576:4576'
      - '4569:4569'
      - '8055:8080'
      - '4572:4572'
      - '4574:4574'
    environment:
      - SERVICES=sns,sqs,kinesis,dynamodb,s3,lambda
      - DEBUG=1
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
volumes:
  db_data:

networks:
  shadow:
    driver: bridge