version: '3.7'

services:
  s3-localstack:
    image: localstack/localstack:latest
    container_name: s3-localstack
    ports:
      - '4572:4572'
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
volumes:
  db_data:

networks:
  shadow:
    driver: bridge